spring:
  application:
    name: tariff-service
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
server:
  port: 8002


management:
  endpoints:
    web:
      exposure:
        include: "*"

